<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$config['base_url'] = '/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = TRUE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = '가-힣a-z 0-9~%.:_\-()';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = 'MTY1NjQw';
$config['password_key'] = 'MTY1NjQwRRcF32';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'session';
$config['sess_expiration'] = 0;
$config['sess_expire_on_close'] = FALSE;
$config['sess_encrypt_cookie'] = TRUE;
$config['sess_use_database'] = TRUE;
$config['sess_table_name'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_match_useragent'] = FALSE;
$config['sess_time_to_update'] = 0;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/

$csrf_off = array(
    "/member/cert_success",
    "/member/cert_fail",
    "/book/upload_file",
    "/book/upload_file",
    "/admin/content/upload_file",
    "/admin/partner/logo_upload_file",
);

if (isset($_SERVER["REQUEST_URI"])) {
    if (in_array($_SERVER["REQUEST_URI"],$csrf_off)) {
        $config['csrf_protection'] = false;
    } else {
        $config['csrf_protection'] = true;
    }
} else {
    $config['csrf_protection'] = true;
}

//$config['csrf_protection'] = false;


/*
$config['csrf_token_name'] = 'seoul_token';
$config['csrf_cookie_name'] = 'csrf_cookie';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();
*/
/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

$config['key'] = "soribox_wyLNG3GwYRRcF32_)(*&^%$#@!";

$config['sms_id'] = "netzeroschool";
$config['sms_key'] = "t96jcm0jfg6uqq00szia7rwxqncx2i9u";


define('NAVER_CLIENT_ID', 'yiZcGj2VtfHCRg8AEzRx');
define('NAVER_CLIENT_SECRET', 'pw4ZRzVhDf');
define('NAVER_CALLBACK_URL', 'https://zero.themvp.kr/member/naver_login_callback');

define('KAKAO_API_KEY','3048a46f7ff3498b7d8c20a28d14fa93');
define('KAKAO_CLIENT_SECRET','bH1jjVlEDUyZDeu7Em3W3GTbUUUsCicd');
define('KAKAO_CALLBACK_URL','https://zero.themvp.kr/member/kakao_login_callback');

define('FACEBOOK_API_KEY','535139685379400');
define('FACEBOOK_CLIENT_SECRET','f87519e4dd08cdcf896757319c57283a');
define('FACEBOOK_CALLBACK_URL','https://zero.themvp.kr/member/facebook_login_callback');

define('PUSH_URL','https://fcm.googleapis.com/v1/projects/lowcarbonschool-2a2d2/messages:send');
define('PUSH_AUTH_KEY','ya29.c.b0Aaekm1Ial4VhFUsYPAENwoYLvLu4DHTyqsPLEcmv3KATfEjfYDKdV26-SF8qMdHMlwOnU3I5JO2hzPlUhl75_YYGYa4nJXEbhGOFPIjKGuTo_C9feOwY9EmA2gKBDqHlFHHd3nr9HnXZNU7krhlkw1bIUAMZhEiSDiDOQM8MtAN-EygK1oebY6Y3hQc8QRrPZ0rVvhfGdipIheDNh-_-DFvPDaJvU_gG232Dshg0z_kZuJRZUIVWM_VwxuWQZXWsXQYxgx9rOq1kQXSrIU5hv1W_BqX-krlm0IlMRdyBpIatR7iMitj8zIbnrqJkUR3b3R2euuxXgQyBn2Oq-Q322wuvc5BrZqVRpW2j6nQRc-kVIk0Y_I7BojVdun3v0o5Z9ftfmbBUFZjahBSf5gjBOuuFeZoVZ7nZYft7e9gF0q4fdi-y2_Q8Sw8cW2ZxZxI8Mdm_qd__evvyMR6oh327FQX4hs9kQSWdvJIXz0wI2qlcrQsk59W0fhiRJcn3Z_Ot1zdg45tdfcR8sxB4fc7I8YFQZr-sB_du82iumZ6tMaB_jlt_g-wMRbuswVb690_bu4a4m7_ziJ6zRqlak70OYdZ7UlFbZF3Ozahk2F5OVwrF04846kqatI6-kpocai2d2OO0_kV5-3ZtsR-eXkz-R4s_ukl_zW0de_Q6gfSwssml5pUyu6e6lzIofopphzIQ6Yx67Xz9ewk42Bhan97g0Vp_ys01WQ_awOVj5z9gIV-VyQi2aFQWYlbFXz8Jf2pi3nfSbdQ3qX2nBnVSzoqJRy6kIp7g8cd5cB8thtFRuxzaMq8g5Ylbd2YyUcpyms729sc5rUIQJs_YodVahJkctxchJzl1rh1xa--hcdoY3vk5lwuihaQ2FdvyUb-Sx21-8-b0orMUcV3-JJtB2f0kekoaZOeB9br5MaqwMs65zMzhJoF5JgafdVjr44-yef1ViqU3y06nBinB252rOhnVOU3jcVBirVb9B15Xt2lhvIBUjaOf0ncopnX');

define('CERT_SITE_CODE','CA690');
define('CERT_PASSWORD','gYO3u8YtS3aJ');


$config['nation'] = array('ANDORRA',
'UNITED ARAB EMIRATES',
'AFGHANISTAN',
'ANTIGUA AND BARBUDA',
'ANGUILLA',
'ALBANIA',
'ARMENIA',
'NETHERLANDS ANTILLES',
'ANGOLA',
'ANTARCTICA',
'ARGENTINA',
'AMERICAN SAMOA',
'AUSTRIA',
'AUSTRALIA',
'ARUBA',
'ALAND ISLANDS',
'AZERBAIJAN',
'BOSNIA HERCEGOVINA',
'BARBADOS',
'BANGLADESH',
'BELGIUM',
'BURKINA FASO',
'BULGARIA',
'BAHRAIN',
'BURUNDI',
'BENIN',
'SAINT BARTHELEMY',
'BERMUDA',
'BRUNEI DARUSSALAM',
'BOLIVIA',
'BONAIRE',
'BRAZIL',
'BAHAMAS',
'BHUTAN',
'BOUVET ISLAND',
'BOTSWANA',
'BELARUS',
'BELIZE',
'CANADA',
'COCOS (KEELING) ISLANDS',
'DEMOCRATIC REPUBLIC OF THE CONGO',
'CENTRAL AFRICAN REPUBLIC',
'CONGO',
'SWITZERLAND',
'COTE D`IVOIRE',
'COOK ISLANDS',
'CHILE',
'CAMEROON',
'CHINA',
'COLOMBIA',
'COSTA RICA',
'CUBA',
'CAPE VERDE',
'CURACAO',
'CHRISTMAS ISLAND',
'CYPRUS',
'CZECH REPUBLIC',
'GERMANY',
'DJIBOUTI',
'DENMARK',
'DOMINICA',
'DOMINICAN REPUBLIC',
'ALGERIA',
'ECUADOR',
'ESTONIA',
'EGYPT',
'WESTERN SAHARA',
'ERITREA',
'SPAIN',
'ETHIOPIA',
'FINLAND',
'FIJI',
'FALKLAND ISLANDS',
'MICRONESIA',
'FAROE ISLANDS',
'FRANCE',
'GABON',
'UNITED KINGDOM',
'GRENADA',
'GEORGIA',
'FRENCH GUIANA',
'GUERNSEY',
'GHANA',
'GIBRALTAR',
'GREENLAND',
'GAMBIA',
'GUINEA',
'GUADELOUPE',
'EQUATORIAL GUINEA',
'GREECE',
'SOUTH GEORGIA AND SOUTH SANDWICH LSLANDS',
'GUATEMALA',
'GUAM',
'GUINEA-BISSAU',
'GUYANA',
'HONG KONG',
'HEARD AND MCDONALD ISLANDS',
'HONDURAS',
'CROATIA',
'HAITI',
'HUNGARY',
'INDONESIA',
'IRELAND',
'ISRAEL',
'ISLE OF MAN',
'INDIA',
'BRITISH INDIAN OCEAN TERRITORY',
'IRAQ',
'IRAN',
'ICELAND',
'ITALY',
'JERSEY',
'JAMAICA',
'JORDAN',
'JAPAN',
'KENYA',
'KYRGYZSTAN',
'CAMBODIA',
'KIRIBATI',
'COMOROS',
'SAINT KITTS AND NEVIS',
'NORTH KOREA',
'SOUTH KOREA',
'KOSOVO',
'KUWAIT',
'CAYMAN ISLANDS',
'KAZAKHSTAN',
'LAOS',
'LEBANON',
'SAINT LUCIA',
'LIECHTENSTEIN',
'SRI LANKA',
'LIBERIA',
'LESOTHO',
'LITHUANIA',
'LUXEMBOURG',
'LATVIA',
'LIBYAN ARAB JAMAHIRIYA',
'MOROCCO',
'MONACO',
'MOLDOVA',
'MONTENEGRO',
'SAINT MARTIN (FRENCH PART)',
'MADAGASCAR',
'MARSHALL ISLANDS',
'MACEDONIA',
'MALI',
'MYANMAR',
'MONGOLIA',
'MACAU',
'NORTHERN MARIANA ISLANDS',
'MARTINIQUE',
'MAURITANIA',
'MONTSERRAT',
'MALTA',
'MAURITIUS',
'MALDIVES',
'MALAWI',
'MEXICO',
'MALAYSIA',
'MOZAMBIQUE',
'NAMIBIA',
'NEW CALEDONIA',
'NIGER',
'NORFOLK ISLAND',
'NIGERIA',
'NICARAGUA',
'NETHERLANDS',
'NORWAY',
'NEPAL',
'NAURU',
'NEUTRAL ZONE',
'NIUE',
'NEW ZEALAND',
'OMAN',
'PANAMA',
'PERU',
'FRENCH POLYNESIA',
'PAPUA NEW GUINEA',
'PHILIPPINES',
'PAKISTAN',
'POLAND',
'SAINT PIERRE AND MIQUELON',
'PITCAIRN',
'PUERTO RICO',
'PALESTINE',
'PORTUGAL',
'PALAU',
'PARAGUAY',
'QATAR',
'REUNION',
'ROMANIA',
'SERBIA',
'RUSSIAN FEDERATION',
'RWANDA',
'SAUDI ARABIA',
'SOLOMON ISLANDS',
'SEYCHELLES',
'SUDAN',
'SWEDEN',
'SINGAPORE',
'SAINT HELENA',
'SLOVENIA',
'SVALBARD AND JAN MAYEN ISLANDS',
'SLOVAKIA',
'SIERRA LEONE',
'SAN MARINO',
'SENEGAL',
'SOMALIA',
'SURINAME',
'SOUTH SUDAN',
'SAO TOME AND PRINCIPE',
'EL SALVADOR',
'SINT MAARTEN (DUTCH PART)',
'SYRIAN ARAB REPUBLIC',
'SWAZILAND',
'TURKS AND CAICOS ISLANDS',
'CHAD',
'FRENCH SOUTHERN TERRITORIES',
'TOGO',
'THAILAND',
'TAJIKISTAN',
'TOKELAU',
'EAST TIMOR',
'TURKMENISTAN',
'TUNISIA',
'TONGA',
'TURKEY',
'TRINIDAD AND TOBAGO',
'TUVALU',
'TAIWAN',
'TANZANIA',
'UKRAINE',
'UGANDA',
'UNITED STATES MINOR OUTLYING ISLANDS',
'UNITED STATES',
'URUGUAY',
'UZBEKISTAN',
'VATICAN CITY STATE',
'SAINT VINCENT AND THE GRENADINES',
'VENEZUELA',
'VIRGIN ISLANDS (BRITISH)',
'VIRGIN ISLANDS (U.S.)',
'VIET NAM',
'VANUATU',
'WALLIS AND FUTUNA ISLANDS',
'SAMOA',
'YEMEN',
'MAYOTTE',
'YUGOSLAVIA',
'SOUTH AFRICA',
'ZAMBIA',
'ZAIRE',
'ZIMBABWE');
